### ISSUE TITLE
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by echan00** [Sxvxgee/Discord-Scraper#4]
What could be the problem?

```
Traceback (most recent call last):
  File "/Users/xxx/Downloads/Discord-Scraper2/source/main.py", line 2, in <module>
    from internal.selfbot import client
  File "/Users/xxx/Downloads/Discord-Scraper2/source/internal/selfbot.py", line 7, in <module>
    client = Client(chunk_guilds_at_startup = False)
TypeError: __init__() missing 1 required keyword-only argument: 'intents'
```

**Comment by solo449** [comment]
get discord.py or just do pip install discord

**Comment by theAbdoSabbagh** [comment]
Adjust the commands to how python is setup in your machine.
```bash
python3 -m pip uninstall discord -y
```
```bash
python3 -m pip install discord.py-self
```

Your error shows that you're using `discord.py` which is a different library than `discord.py-self`. This library uses `discord.py-self`, a version of `discord.py` but for selfbots, aka user accounts.
