### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed

### ISSUE THREAD

**Issue by rech2020** [Sxvxgee/Discord-Scraper#7]
```
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 1058, in static_login
    data = await self.get_me()
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 934, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/DiscordScraper/source/main.py", line 9, in <module>
    client.run(config["token"]) # type: ignore
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 1106, in run
    asyncio.run(runner())
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 1095, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 1025, in start
    await self.login(token)
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/client.py", line 867, in login
    data = await state.http.static_login(token.strip())
  File "/home/codespace/.local/lib/python3.10/site-packages/discord/http.py", line 1062, in static_login
    raise LoginFailure('Improper token has been passed') from exc
discord.errors.LoginFailure: Improper token has been passed
```

**Comment by w2zyx** [comment]
it can be old code
